---
svn:
  url: "svn://127.0.0.1"
  username: "fake"
  password: "book"
  local_path: "/path/to/somewhere"
s3:
  access_key_id: "access-key-id"
  secret_access_key: "secret-access-key"
  bucket: "bucket"
  key: "key"

